backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'product'
    label: 'Товар'
    folder: 'content/products'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
      - { label: 'Опубликовано', name: 'date', widget: 'datetime' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Цена', name: 'price', widget: 'number', min: 0 }
      - {
          label: 'За штуку',
          name: 'perItem',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Картинка', name: 'image', widget: 'image' }
